Update rebuild

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -23,9 +23,9 @@
 #
 # init_var           : Initialize all variables
 # find_armbian       : Find Armbian file (build/output/images/*.img)
+# download_depends   : Download the dependency files
 # query_version      : Query the latest kernel version
 # download_kernel    : Download the latest kernel
-# download_depends   : Download the dependency files
 #
 # confirm_version    : Confirm version type
 # extract_armbian    : Extract Armbian files
@@ -63,7 +63,7 @@ host_release="$(cat /etc/os-release | grep '^VERSION_CODENAME=.*' | cut -d'=' -f
 os_release_file="etc/os-release"
 # Set banner's ${BOARD_NAME}: such as [ s905x3 ]
 armbian_release_file="etc/armbian-release"
-# Add custom armbian firmware information
+# Add custom armbian information
 ophub_release_file="etc/ophub-release"
 
 # Firmware files download repository
@@ -72,17 +72,16 @@ firmware_repo="https://github.com/ophub/firmware/tree/main/firmware"
 firmware_repo="${firmware_repo//tree\/main/trunk}"
 
 # Kernel files download repository
-kernel_repo="https://github.com/Anywherexu/kernel/releases/tag"
-# kernel_repo="https://github.com/ophub/kernel/tree/main/pub"
-# Convert kernel library address to svn format
-kernel_repo="${kernel_repo//tree\/main/trunk}"
-# Common kernel directory, RK3588 kernel directory, [ rk3588 ] is the fixed name
-kernel_dir=("stable")              # "rk3588"
-common_kernel=("6.0.10" "5.19.17")
-# rk3588_kernel=("5.10.150")
+kernel_repo="https://github.com/ophub/kernel/tree/main/pub"
+# Set stable kernel directory: [ stable ], rk35xx kernel directory: [ rk3588 ]
+kernel_dir=("stable" "rk3588")
+# Set the list of kernels used by default
+stable_kernel=("6.0.10" "5.15.50")
+rk35xx_kernel=("5.10.150")
+# Set to automatically use the latest kernel
 auto_kernel="true"
 
-# Set supported board
+# Set the list of supported armbian board
 build_armbian=(
     "a311d"
     "s922x" "s922x-n2" "s922x-reva"
@@ -98,21 +97,28 @@ build_armbian=(
     "r66s" "r68s"
     "beikeyun" "l1pro"
 )
+# Set the list of devices that must use the rk35xx kernel
+must_kernel_rk35xx=("rock5b")
+# Set the list of devices that must use the stable/6.x.y kernel
+must_kernel_6xy=("r66s" "r68s")
 
-# Set Armbian firmware size (Unit: MiB, BOOT_MB >= 256, ROOT_MB >= 2048)
+# Set Armbian size (Unit: MiB, BOOT_MB >= 256, ROOT_MB >= 2048)
 BOOT_MB="256"
-ROOT_MB="5120"
+ROOT_MB="2560"
 # Set ROOTFS partition file system type, options: [ ext4 / btrfs ]
 ROOTFS_TYPE="ext4"
-# Custom name in firmware name: ${build_image_file}, such as _server, _dev, etc.
+# Custom name in Armbian file: ${build_image_file}, such as _server, _dev, etc.
 custom_name="_server"
+
+# Get gh_token for api.github.com
+gh_token=""
 
 # Set font color
 STEPS="[\033[95m STEPS \033[0m]"
 INFO="[\033[94m INFO \033[0m]"
-SUCCESS="[\033[92m SUCCESS \033[0m]"
-PROMPT="[\033[93m PROMPT \033[0m]"
+TIPS="[\033[93m TIPS \033[0m]"
 WARNING="[\033[93m WARNING \033[0m]"
+SUCCESS="[\033[92m SUCCESS \033[0m]"
 ERROR="[\033[91m ERROR \033[0m]"
 #
 #========================================================================================
@@ -137,7 +143,7 @@ init_var() {
     echo -e "${STEPS} Start Initializing Variables..."
 
     # If it is followed by [ : ], it means that the option requires a parameter value
-    get_all_ver="$(getopt "b:k:a:v:s:t:n:" "${@}")"
+    get_all_ver="$(getopt "b:k:a:v:r:s:t:n:g:" "${@}")"
 
     while [[ -n "${1}" ]]; do
         case "${1}" in
@@ -159,7 +165,7 @@ init_var() {
             if [[ -n "${2}" ]]; then
                 oldIFS=${IFS}
                 IFS=_
-                common_kernel=(${2})
+                stable_kernel=(${2})
                 IFS=${oldIFS}
                 shift
             else
@@ -186,6 +192,14 @@ init_var() {
                 error_msg "Invalid -v parameter [ ${2} ]!"
             fi
             ;;
+        -r | --KernelRepository)
+            if [[ -n "${2}" ]]; then
+                kernel_repo="${2}"
+                shift
+            else
+                error_msg "Invalid -r parameter [ ${2} ]!"
+            fi
+            ;;
         -s | --Size)
             if [[ -n "${2}" && "${2}" -ge "2048" ]]; then
                 ROOT_MB="${2}"
@@ -210,12 +224,23 @@ init_var() {
                 error_msg "Invalid -n parameter [ ${2} ]!"
             fi
             ;;
+        -g | --gh_token)
+            if [[ -n "${2}" ]]; then
+                gh_token="${2}"
+                shift
+            else
+                error_msg "Invalid -g parameter [ ${2} ]!"
+            fi
+            ;;
         *)
             error_msg "Invalid option [ ${1} ]!"
             ;;
         esac
         shift
     done
+
+    # Convert kernel library address to svn format
+    kernel_repo="${kernel_repo//tree\/main/trunk}"
 }
 
 find_armbian() {
@@ -236,6 +261,14 @@ find_armbian() {
     echo -e "${INFO} Armbian rebuild file: [ ${armbian_rebuild_name} ], Version: [ ${armbian_rebuild_version} ]"
 }
 
+download_depends() {
+    cd ${make_path}
+    echo -e "${STEPS} Start downloading dependency files..."
+
+    # Download Armbian firmware files
+    svn co ${firmware_repo} ${firmware_path} --force
+}
+
 query_version() {
     echo -e "${STEPS} Start querying the latest kernel version..."
 
@@ -250,9 +283,9 @@ query_version() {
         {
             # Select the corresponding kernel directory and list
             if [[ "${k}" == "rk3588" ]]; then
-                down_kernel_list="${rk3588_kernel[*]}"
+                down_kernel_list="${rk35xx_kernel[*]}"
             else
-                down_kernel_list="${common_kernel[*]}"
+                down_kernel_list="${stable_kernel[*]}"
             fi
 
             # Query the name of the latest kernel version
@@ -260,34 +293,45 @@ query_version() {
             i=1
             for kernel_var in ${down_kernel_list[*]}; do
                 echo -e "${INFO} (${x}.${i}) Auto query the latest kernel version of the same series for [ ${k} - ${kernel_var} ]"
+
+                # Identify the kernel mainline
                 MAIN_LINE="$(echo ${kernel_var} | awk -F '.' '{print $1"."$2}')"
+
                 # Check the version on the server (e.g LATEST_VERSION="125")
-                LATEST_VERSION="$(curl -s "${server_kernel_url}/${k}" | grep "name" | grep -oE "${MAIN_LINE}.[0-9]+" | sed -e "s/${MAIN_LINE}.//g" | sort -n | sed -n '$p')"
+                if [[ -n "${gh_token}" ]]; then
+                    LATEST_VERSION="$(curl --header "authorization: Bearer ${gh_token}" -s "${server_kernel_url}/${k}" | grep "name" | grep -oE "${MAIN_LINE}.[0-9]+" | sed -e "s/${MAIN_LINE}.//g" | sort -n | sed -n '$p')"
+                    query_api="Authenticated user request"
+                else
+                    LATEST_VERSION="$(curl -s "${server_kernel_url}/${k}" | grep "name" | grep -oE "${MAIN_LINE}.[0-9]+" | sed -e "s/${MAIN_LINE}.//g" | sort -n | sed -n '$p')"
+                    query_api="Unauthenticated user request"
+                fi
+
                 if [[ "${?}" -eq "0" && -n "${LATEST_VERSION}" ]]; then
                     tmp_arr_kernels[${i}]="${MAIN_LINE}.${LATEST_VERSION}"
                 else
                     tmp_arr_kernels[${i}]="${kernel_var}"
                 fi
-                echo -e "${INFO} (${x}.${i}) [ ${k} - ${tmp_arr_kernels[$i]} ] is latest kernel. \n"
+
+                echo -e "${INFO} (${x}.${i}) [ ${k} - ${tmp_arr_kernels[$i]} ] is latest kernel (${query_api}). \n"
 
                 let i++
             done
 
             # Reset the kernel array to the latest kernel version
             if [[ "${k}" == "rk3588" ]]; then
-                unset rk3588_kernel
-                rk3588_kernel="${tmp_arr_kernels[*]}"
+                unset rk35xx_kernel
+                rk35xx_kernel="${tmp_arr_kernels[*]}"
             else
-                unset common_kernel
-                common_kernel="${tmp_arr_kernels[*]}"
+                unset stable_kernel
+                stable_kernel="${tmp_arr_kernels[*]}"
             fi
 
             let x++
         }
     done
 
-    echo -e "${INFO} The latest version of the common_kernel: [ ${common_kernel[*]} ]"
-    echo -e "${INFO} The latest version of the rk3588_kernel: [ ${rk3588_kernel[*]} ]"
+    echo -e "${INFO} The latest version of the stable_kernel: [ ${stable_kernel[*]} ]"
+    echo -e "${INFO} The latest version of the rk35xx_kernel: [ ${rk35xx_kernel[*]} ]"
 }
 
 download_kernel() {
@@ -299,9 +343,9 @@ download_kernel() {
         {
             # Set the kernel download list
             if [[ "${k}" == "rk3588" ]]; then
-                down_kernel_list="${rk3588_kernel[*]}"
+                down_kernel_list="${rk35xx_kernel[*]}"
             else
-                down_kernel_list="${common_kernel[*]}"
+                down_kernel_list="${stable_kernel[*]}"
             fi
 
             # Download the kernel to the storage directory
@@ -321,18 +365,6 @@ download_kernel() {
             let x++
         }
     done
-}
-
-download_depends() {
-    cd ${make_path}
-    echo -e "${STEPS} Start downloading dependency files..."
-
-    # Download armbian firmware files
-    if [[ -d "${firmware_path}" ]]; then
-        svn up ${firmware_path} --force
-    else
-        svn co ${firmware_repo} ${firmware_path} --force
-    fi
 }
 
 confirm_version() {
@@ -379,10 +411,10 @@ confirm_version() {
         # Set the type of file system
         if [[ "${ROOTFS_TYPE}" == "btrfs" ]]; then
             uenv_rootdev="UUID=${ROOTFS_UUID} rootflags=compress=zstd:6 rootfstype=btrfs"
-            fstab_string="defaults,noatime,compress=zstd:6"
+            fstab_string="discard,defaults,noatime,compress=zstd:6"
         else
             uenv_rootdev="UUID=${ROOTFS_UUID} rootflags=data=writeback rw rootfstype=ext4"
-            fstab_string="defaults,noatime,errors=remount-ro"
+            fstab_string="discard,defaults,noatime,errors=remount-ro"
         fi
     }
 
@@ -401,11 +433,11 @@ confirm_version() {
         if [[ "${ROOTFS_TYPE}" == "btrfs" ]]; then
             uenv_rootflags="compress=zstd:6"
             uenv_rootdev="UUID=${ROOTFS_UUID}"
-            fstab_string="defaults,noatime,compress=zstd:6"
+            fstab_string="discard,defaults,noatime,compress=zstd:6"
         else
             uenv_rootflags="rw,errors=remount-ro"
             uenv_rootdev="UUID=${ROOTFS_UUID}"
-            fstab_string="defaults,noatime,commit=600,errors=remount-ro"
+            fstab_string="discard,defaults,noatime,commit=600,errors=remount-ro"
         fi
     }
 }
@@ -424,9 +456,8 @@ extract_armbian() {
     loop_old="$(losetup -P -f --show "${armbian_image_file}")"
     [[ -n "${loop_old}" ]] || error_msg "losetup ${armbian_image_file} failed."
 
-    if ! mount ${loop_old}p1 ${tmp_armbian}; then
-        error_msg "mount ${loop_old}p1 failed!"
-    fi
+    mount -o discard ${loop_old}p1 ${tmp_armbian}
+    [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_old}p1 failed!"
 
     cd ${tmp_armbian}
 
@@ -513,12 +544,21 @@ copy_files() {
     tag_rootfs="${tmp_build}/rootfs"
     mkdir -p ${tag_bootfs} ${tag_rootfs}
 
-    if ! mount -o discard ${loop_new}p1 ${tag_bootfs}; then
-        error_msg "mount ${loop_new}p1 failed!"
+    # Mount bootfs
+    if [[ "${PLATFORM}" == "amlogic" ]]; then
+        mount -t vfat -o discard ${loop_new}p1 ${tag_bootfs}
+    else
+        mount -t ext4 -o discard ${loop_new}p1 ${tag_bootfs}
     fi
-    if ! mount -o discard ${loop_new}p2 ${tag_rootfs}; then
-        error_msg "mount ${loop_new}p2 failed!"
+    [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_new}p1 failed!"
+
+    # Mount rootfs
+    if [[ "${ROOTFS_TYPE}" == "btrfs" ]]; then
+        mount -t btrfs -o discard,compress=zstd:6 ${loop_new}p2 ${tag_rootfs}
+    else
+        mount -t ext4 -o discard ${loop_new}p2 ${tag_rootfs}
     fi
+    [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_new}p2 failed!"
 
     # Copy the full Armbian image
     cp -af ${tmp_armbian}/* ${tag_rootfs}
@@ -624,6 +664,13 @@ refactor_files() {
     rm -rf usr/lib/linux-image-*
     rm -f usr/sbin/ddbr
     rm -f var/lib/dpkg/info/linux-image*
+    # Remove motd-news related services
+    rm -f usr/lib/systemd/system/motd-news.timer
+    rm -f usr/lib/systemd/system/motd-news.service
+    rm -f var/lib/systemd/deb-systemd-helper-enabled/timers.target.wants/motd-news.timer
+    rm -f var/lib/systemd/deb-systemd-helper-enabled/motd-news.timer.dsh-also
+    rm -f etc/systemd/system/timers.target.wants/motd-news.timer
+    rm -f etc/update-motd.d/50-motd-news
 
     # Rebuild symbolic link files (ln -sf ${target} ${symbolic_link_file})
     ln -sf /usr/bin bin
@@ -652,7 +699,7 @@ refactor_files() {
     [[ -f "usr/libexec/sudo/sudoers.so" ]] && chmod 644 usr/libexec/sudo/sudoers.so
     [[ -f "usr/libexec/polkit-agent-helper-1" ]] && chmod 4755 usr/libexec/polkit-agent-helper-1
 
-    # Add custom firmware information
+    # Add custom Armbian information
     echo "PLATFORM='${PLATFORM}'" >>${ophub_release_file}
     echo "VERSION_CODEID='${release_codeid}'" >>${ophub_release_file}
     echo "VERSION_CODENAME='${release_codename}'" >>${ophub_release_file}
@@ -686,7 +733,7 @@ refactor_files() {
     # Edit the etc/fstab
     [[ -f "etc/fstab" ]] || error_msg "The etc/fstab File does not exist."
     sed -i "s|LABEL=ROOTFS.*|UUID=${ROOTFS_UUID}  /      ${ROOTFS_TYPE}  ${fstab_string}  0 1|g" etc/fstab
-    [[ "${PLATFORM}" == "rockchip" ]] && sed -i "s|LABEL=BOOT.*|UUID=${BOOT_UUID}  /boot  ext4  defaults  0 2|g" etc/fstab
+    [[ "${PLATFORM}" == "rockchip" ]] && sed -i "s|LABEL=BOOT.*|UUID=${BOOT_UUID}  /boot  ext4  discard,defaults  0 2|g" etc/fstab
 
     # Update release information
     [[ -f "${armbian_release_file}" ]] && {
@@ -696,10 +743,10 @@ refactor_files() {
         sed -i "s|IMAGE_TYPE=.*|IMAGE_TYPE=stable|g" ${armbian_release_file}
     }
 
-    # Clear quotes content for [ /etc/update-motd.d/35-armbian-tips ]
-    quotes_file="etc/update-motd.d/quotes.txt"
+    # Disable tips of the day for [ /etc/update-motd.d/35-armbian-tips ]
+    motd_tips="etc/default/armbian-motd"
+    [[ -f "${motd_tips}" ]] && sed -i 's|^MOTD_DISABLE=.*|MOTD_DISABLE="tips"|g' ${motd_tips}
     quotes_cron="etc/cron.weekly/armbian-quotes"
-    [[ -f "${quotes_file}" ]] && echo "" >${quotes_file}
     [[ -f "${quotes_cron}" ]] && sed -i "s|^curl |#curl |g" ${quotes_cron}
 
     # Make the .bashrc take effect, Default shell settings file: /etc/default/useradd
@@ -795,7 +842,7 @@ clean_tmp() {
 
     cd ${tmp_outpath}
 
-    pigz -9f *.img && mv -f *.img.gz ${armbian_outputpath} && sync
+    pigz -f *.img && mv -f *.img.gz ${armbian_outputpath} && sync
 
     cd ${make_path}
 
@@ -804,7 +851,7 @@ clean_tmp() {
 
 loop_rebuild() {
     cd ${make_path}
-    echo -e "${STEPS} Start building Armbian firmware..."
+    echo -e "${STEPS} Start building Armbian..."
 
     j="1"
     for b in ${build_armbian[*]}; do
@@ -813,27 +860,27 @@ loop_rebuild() {
             confirm_version
 
             # Determine kernel branch
-            if [[ "${KERNEL_BRANCH}" == "rk3588" ]]; then
-                build_kernel="${rk3588_kernel[*]}"
+            if [[ -n "$(echo "${must_kernel_rk35xx[@]}" | grep -w "${board}")" ]]; then
+                kernel_list="${rk35xx_kernel[*]}"
                 kd="rk3588"
             else
-                build_kernel="${common_kernel[*]}"
+                kernel_list="${stable_kernel[*]}"
                 kd="$(echo "${kernel_dir[@]}" | sed -e "s|rk3588||" | xargs)"
             fi
 
             i="1"
-            for k in ${build_kernel[*]}; do
+            for k in ${kernel_list[*]}; do
                 {
                     kernel="${k}"
 
-                    # Rockchip rk3568 series, such as FastRhino R66S/R68S only support 6.0.y and above kernel
-                    [[ "${SOC,,}" == "rk3568" && "${kernel:0:1}" -ne "6" ]] && {
-                        echo -e "(${j}.${i}) ${PROMPT} ${board}(${SOC,,}) cannot use ${kernel} kernel, skip."
+                    # Identify devices that must use the 6.x.y kernel
+                    [[ -n "$(echo "${must_kernel_6xy[@]}" | grep -w "${board}")" && "${kernel:0:1}" -ne "6" ]] && {
+                        echo -e "(${j}.${i}) ${TIPS} The ${board} device cannot use ${kd}/${kernel} kernel, skip."
                         let i++
                         continue
                     }
 
-                    echo -ne "(${j}.${i}) Start building Armbian [ ${b} - ${kd}/${k} ]. "
+                    echo -ne "(${j}.${i}) Start building Armbian [ ${board} - ${kd}/${kernel} ]. "
                     now_remaining_space="$(df -Tk ${make_path} | grep '/dev/' | awk '{print $5}' | echo $(($(xargs) / 1024 / 1024)))"
                     if [[ "${now_remaining_space}" -le "6" ]]; then
                         echo -e "${WARNING} Remaining space is less than 6G, exit this build."
@@ -873,24 +920,23 @@ echo -e "${INFO} Server running on Ubuntu: [ Release: ${host_release} / Host: ${
 echo -e "${INFO} Server CPU configuration information: \n$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
 echo -e "${INFO} Server memory usage: \n$(free -h) \n"
 echo -e "${INFO} Server space usage before starting to compile: \n$(df -hT ${make_path}) \n"
-echo -e "${INFO} Setting parameters: [ ${@} ] \n"
 #
 # Initialize variables
 init_var "${@}"
 # Find rebuild files
 find_armbian
+# Download the dependency files
+download_depends
 # Download the latest kernel
 [[ "${auto_kernel}" == "true" ]] && query_version
 download_kernel
-# Download the dependency files
-download_depends
 #
-echo -e "${INFO} Armbian Board List: [ $(echo ${build_armbian[*]} | tr "\n" " ") ]"
-echo -e "${INFO} COMMON Kernel List: [ $(echo ${common_kernel[*]} | tr "\n" " ") ]"
-echo -e "${INFO} RK3588 Kernel List: [ $(echo ${rk3588_kernel[*]} | tr "\n" " ") ]"
-echo -e "${INFO} ROOTFS Type: [ ${ROOTFS_TYPE} ] \n"
+echo -e "${INFO} Armbian board list: [ $(echo ${build_armbian[*]} | tr "\n" " ") ]"
+echo -e "${INFO} Stable kernel list: [ $(echo ${stable_kernel[*]} | tr "\n" " ") ]"
+echo -e "${INFO} Rk35xx Kernel list: [ $(echo ${rk35xx_kernel[*]} | tr "\n" " ") ]"
+echo -e "${INFO} ROOTFS type: [ ${ROOTFS_TYPE} ] \n"
 #
-# Loop to rebuild armbian firmware
+# Loop to rebuild armbian
 loop_rebuild
 #
 # Show server end information
